export type SightingData = {
    id: number,
    latitude: number,
    longitude: number,
    individualCount: number,
    species: string,
    vernacularName: string,
    basisOfRecord: string,
    coordinateUncertaintyInMeters: number,
    dateIdentified: string,
    year: string,
    day: string,
    month: string,
    locality: string,
    waterBody: string,
    identificationRemarks: string,
    shoredistance: number,
    type: string,
}